markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:year/:month/:title/
paginate: 5

title: Development, design, and more by David Ensinger
author: David Ensinger
email: hello@davidensinger.com
description: David Ensinger is a Front End Developer from Columbus, OH
url: http://davidensinger.com

exclude: ["config.json", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "scss", "Termfile"]
